### ISSUE TITLE
Do not serialize PlayerStorage

### ISSUE THREAD

**Issue by schr3j** [ET-Bent/CoreIO#13]
The [PlayerStorage](https://github.com/ET-Bent/CoreIO/blob/master/src/main/java/com/unitedworldminers/CoreIO/util/PlayerStorage.java) is currently serialized and written into a file. This is quite unsafe as the file may not be able to load when PlayerStorage is changed. This would result in a data loss.
Instead the PlayerStorage should be saved into a yaml file. Either one for all users or seperate files per user.

**Comment by deregges** [comment]
Implemented in a10f544
