### ISSUE TITLE
Weird NPE

### ISSUE THREAD

**Issue by Towsty** [ET-Bent/CoreIO#5]
I get this crash from time to time. Most typically it happens when I log our of a SSP world, and try to log back in without restarting the client. However, this paste is actually from a server. I forgot to remove a mod from the server before I rebooted it, when I logged in I got kicked with a mod mismatch. After I was booted the server crashed with this error. 

http://pastebin.com/jZCTVdBL

**Comment by deregges** [comment]
Yeah this bug is already fixed in f6fa2cc. I'll build a new version as early as i can

**Comment by Towsty** [comment]
Great, lookin forward to it! Thanks for the response.
