### ISSUE TITLE
Disconnect/Boot from world SSP and SMP w/ CoreIO 0.4.9.0

### ISSUE THREAD

**Issue by Towsty** [ET-Bent/CoreIO#7]
Get a critical exception when connecting to any type of world it seems. See server log:

https://www.dropbox.com/s/k2ru07vsiuyn620/fml-server-latest.log?dl=0

**Comment by deregges** [comment]
Fixed in 3e95c8f. Will build in ~8h

**Comment by deregges** [comment]
Okay, the new file is up now (Replaced -> same version). Grab it, this time I've tested it...

**Comment by Towsty** [comment]
Sounds good! Thanks
