### ISSUE TITLE
Perms Inheritance

### ISSUE THREAD

**Issue by Towsty** [ET-Bent/CoreIO#9]
I may be misunderstanding how this works but it seems like the inherits property in different perm groups does not do anything.

The way I understand it is (all examples, I know they are not proper perms):
Commands you can access:
Users:
 - home
 - tps
moderators (inherits users therefore has access to home and tps) and the following:
 - mute
 - ban
 - kick
admin (inherits moderators and users so has access to all commands in both groups) and the following:
 - op
 - deop
 - weather

However it seems like different tiers don't actually inherit the commands from the previous groups.
On my server we have technicians as default, engineers as a sort of moderator type group, and ceo as owner/lead admin. CEO -> inherits engineer -> inherits technician. In order for ceo to use commands in the technician group I had to add the user to both ceo, and technician, as well as default. Not sure if this is intentional or not.

**Comment by deregges** [comment]
Inheritance should work the way you said...
I'll look into it but first let me eat a little ^^

**Comment by deregges** [comment]
Fixed in 338a340 - CoreIO-0.5.1.0. *awaiting new issues*

**Comment by Towsty** [comment]
Woot!
